import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ziyang.ca',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" media="(prefers-color-scheme: light)"/>
        <link rel="icon" href="/icon-dark.png" media="(prefers-color-scheme: dark)"/>
      </head> 
      <body className={inter.className}>{children}</body>
    </html>
  )
}
